### ISSUE TITLE
Jupyter Server Proxy widget for conda-store

### ISSUE THREAD

**Issue by costrouc** [Quansight/conda-store#102]
As a first step towards a jupyterlab extension for conda-store. 

The idea is to expose conda-store similarly to how code-server is exposed on jupyterlab via https://github.com/dirkcgrunwald/jupyter_codeserver_proxy-/blob/master/setup.py. See https://github.com/dirkcgrunwald/jupyter_codeserver_proxy-/blob/master/jupyter_codeserver_proxy/__init__.py. Upon further investigation I'm not sure if it is possible with jupyter-server-proxy or the best route since we really only need to add a link to jupyterlab.

# Acceptance Criteria

 - user is able to visit jupyterlab and click on an icon in the lancher that takes them to `https://<conda-store-url>/`

**Comment by saulshanabrook** [comment]
Using the jupyter server proxy, it seems like we have two options:

1.  Launch conda store alongside jupyter. This is probably not how you are doing things now, but could be a good proof of concept getting started mode. In that case, all the user would have to do is `pip install conda-store; jupyter lab` and then it would start up once they visited `localhost:8888/conda-store`. This is nice, because Jupyter now will take care of launching and killing the conda store proxy and making it available.
2.  Have jupyter server proxy instead launch a proxy that proxies the conda store to wherever it is already running. This could make sense in more of an enterprise/multi tenant setting, where you want to manage the conda store process separately from the jupyter process. However, I think it still could be advantageous since it will proxy the conda store to a sub URL, so it will be accessible to anyone who can access the jupyter port.

For ease of testing and getting started, one option could be to default to 1. (pending proper packaging of the conda store to allow it to be pip installable and runnable as a standalone process), and then support 2 with a env variable the user could set, like `CONDA_STORE_URL` or something, that if set, would just run a proxy?

**Comment by costrouc** [comment]
Is there a simple approach that would not require jupyter-server-proxy? I'd like if we could just redirect the user. Similar to the `Hub Control Panel` file selection.

![image](https://user-images.githubusercontent.com/1740337/129096530-680298da-eaa4-487c-b378-2f7b111af638.png)

**Comment by saulshanabrook** [comment]
You can write a jupyterlab extension for that if you want. The server proxy is the only technique I know where you don't have to write an extension
