### ISSUE TITLE
a DELETE Environment API endpoint is needed

### ISSUE THREAD

**Issue by pierrotsmnrd** [Quansight/conda-store#124]
The original Gator project (the base for the Conda Store UI) allows the user to delete an environment.

I didn't find any DELETE or similar endpoint in the docs.

**Comment by costrouc** [comment]
Giving some context around this issue. Currently conda-store has a permissions model around envioroments where there is a https://github.com/Quansight/conda-store/blob/main/conda-store-server/conda_store_server/server/auth.py#L30.


```


class Permissions(enum.Enum):
    ENVIRONMENT_CREATE = "build::create"
    ENVIRONMENT_READ = "build::read"
    ENVIRONMENT_UPDATE = "build::update"
    ENVIRONMENT_DELETE = "build::delete"
```

My guess is that we will need to add an `environment::delete` permission and by default add this to the `admin` role. This should be easy to add along with the required UI buttons etc.

However as for the larger issue on thinking about this. What should the `delete` environment action do?

My first thoughts are that is should delete **everything** within that environment e.g. all builds, logs, artifacts. Currently I have the `build::delete` action to do a "soft" deletion where not everything is deleted see https://github.com/Quansight/conda-store/blob/40f27ba350f0e2a82c1bae571240763e2618f5bb/conda-store-server/conda_store_server/app.py#L72. Here logs, lockfile, and yaml are kept. My guess is this action would be destructive and everything is deleted. 

@pierrotsmnrd thoughts?

**Comment by pierrotsmnrd** [comment]
I see multiple use cases for deletion : remove a test env, or an old env not used anymore, or the need to save space etc. 

In all these cases :  I think deletion should mean absolute deletion :) It should delete the builds, the artifacts, yaml, logs, lockfiles. An environment should not be considered deleted as long as any of its artefacts remain.


Regarding the permissions, it raises the question of passing auth to the API. What's the mechanism here ? 
I guess it will also imply having a mechanism let the user auth from the UI - I'll open an issue on the UI project once this is confirmed.

**Comment by costrouc** [comment]
I've added docs for the [authentication model](https://conda-store.readthedocs.io/en/latest/contributing.html#authentication-model) and [authorization model](https://conda-store.readthedocs.io/en/latest/contributing.html#authorization-model) since I neglected to mention this. 

> Regarding the permissions, it raises the question of passing auth to the API. What's the mechanism here ?

Right now for testing I'd suggest we modify the unauthenticated user or service default role bindings in the configuration [see here](https://github.com/Quansight/conda-store/blob/main/conda-store-server/conda_store_server/server/auth.py#L87) but we can just set this in configuration for testing. I'd change this to `"*/*": {"admin"}`. 

But yes you are right that authentication will need to be addressed in gator at some point in near the future.

I'm glad we both agree on what deleting an environment means. I think this makes this issue now well specified and ready for a PR.
