### ISSUE TITLE
Feature : List installed packages of a given env

### ISSUE THREAD

**Issue by pierrotsmnrd** [Quansight/conda-store#134]
**Goal :** 
- Port the following feature of Gator using Conda Store : **List installed packages of a given env**

**Acceptance :**  
- The feature works with mamba/conda and Conda Store 

**Other notes :** 
Show the packages with their version and channel

**Comment by peytondmurray** [comment]
Blocked by https://github.com/Quansight/conda-store/issues/150, which should modify the existing endpoint for retrieving packages. I think in priniciple I will send a request to `/api/v1/builds/<build_id>/` for a paginated list of packages, rather than the existing endpoint `/api/v1/namespace/<namespace>/environments/<environment/`.

**Comment by pierrotsmnrd** [comment]
Now that #150 is close, I remove the blocked label.

**Comment by pierrotsmnrd** [comment]
We need to fix the checkbox to invert its state.

**Comment by peytondmurray** [comment]
Merged: https://github.com/mamba-org/gator/pull/155
