### ISSUE TITLE
Feature : Remove a package from a given env

### ISSUE THREAD

**Issue by pierrotsmnrd** [Quansight/conda-store#136]
**Goal :** 
- Port the following feature of Gator using Conda Store : **Remove a package from a given env**

**Acceptance :**  
- The feature works with mamba/conda and Conda Store

**Comment by pierrotsmnrd** [comment]
After discussing with Chris during today's meeting, my previous comment is invalid : only the second step is needed.

➞ update the env this way (`PUT /api/v1/environment/<namespace>/<name>/ `)

**Comment by peytondmurray** [comment]
Blocked by the following:

* Testing/merge of  https://github.com/Quansight/conda-store/issues/132 (), which has been approved but Frederic cannot merge it because he cannot test it.
* Conda-store currently requires authentication and authorization to post new build specifications for environments. I think this should be changed to only require authorization.

**Comment by peytondmurray** [comment]
Blocked by #202.

**Comment by pierrotsmnrd** [comment]
Blocked in a similar way to #135

**Comment by peytondmurray** [comment]
Merged: https://github.com/mamba-org/gator/pull/166
