### ISSUE TITLE
API : List of packages `/api/v1/package/` shows duplicated results should return more information so that client can dedup

### ISSUE THREAD

**Issue by pierrotsmnrd** [Quansight/conda-store#151]
As reported by @peytondmurray on slack, the `/api/v1/package/` endpoint returns packages multiple times, with the same name and same version : 

```
  {'channel_id': 1,
   'id': 98,
   'license': 'Apache 2.0',
   'name': 'absl-py',
   'sha256': '6b5362e8e3338b35574a31964a12a48bda4e8f3703cf8760c85cb6f8714811e4',
   'summary': 'Abseil Python Common Libraries, see https://github.com/abseil/abseil-py.',
   'version': '0.10.0'},
  {'channel_id': 1,
   'id': 99,
   'license': 'Apache 2.0',
   'name': 'absl-py',
   'sha256': '2325d0d914119c24a5617faa344665d525d8c4642fcfc149e48d4f78d6338494',
   'summary': 'Abseil Python Common Libraries, see https://github.com/abseil/abseil-py.',
   'version': '0.10.0'},
  {'channel_id': 1,
   'id': 100,
   'license': 'Apache 2.0',
   'name': 'absl-py',
   'sha256': '36e780d858d6bd41a3342645500ed316da8f2314cf4b3a25821ee0fc9097a366',
   'summary': 'Abseil Python Common Libraries, see https://github.com/abseil/abseil-py.',
   'version': '0.10.0'}
```

The hypothesis is they are different _builds_. 
The fix then is to show the latest, highest built.

**Comment by costrouc** [comment]
Was looking at the database to see why we are getting these particular results

![image](https://user-images.githubusercontent.com/1740337/133848834-017b427f-431b-4c98-80c6-7255a7c263ab.png)

So there are `python` 3.6, 2.7, etc. builds for each given conda package. 

Question is how should we handle duplicates in the api? My answer would be that it shouldn't be the api's job to dedupe these since it may be useful for the client. Instead I think that we should return more information about the given package to dedup.

Thoughts? @pierrotsmnrd and @peytondmurray

**Comment by peytondmurray** [comment]
Totally agree with you, with the condition that the API should provide the client a way of distinguishing them (maybe with a `platform` attribute or similar?). Right now all we have is a difference in the hash, so there's no way of distinguishing them.

That said, practically speaking the user will not care if there's a 3.6 version and a 3.7 version and a 3.8 version of `numpy` or whatever package, will they? They will specify an environment like this:

```yaml
name: test-env
dependencies:
  - python==3.7
  - numpy
```

and nowhere in here will they specify what platform to use for the `numpy` package - that's determined by the python version. Essentially all the user will care about is the name of the package and its version, because that's what they'll use to install the package and google its documentation. If the conda-store API doesn't dedupe these, we'll have to do it on the frontend anyway.

**Comment by pierrotsmnrd** [comment]
Sure, a user specifying his env with a yml will not care if there's a 3.6 or 3.7 version of his package, he will just write `numpy` and that's all. But writing the yml file to describe the env is not like listing available packages. it's two separate steps, features, and we're leaving the realm of the API itself.

In the context of Gator, we need to rely on the API and it must be flexible enough so we can make it work.
The API must remain flexible enough though for other tools to plug in (i.e. the API must not be Gator specific)

Then, I suggest : 
- the API result should contain a `python` field with values like `"3.6"`, `"3.7"` ... That way, the API user will understand the results are not duplicates.
- similarly, the `api/v1/package` should also accept a `python` parameter to filter on the python versions. accepted values would be like `3.7` (exactly python3.7), `>=3.5` (python >= 3.5). The only accepted comparison operators would be nothing for equality, `>, >=,<, <=`

Thoughts ? :)

**Comment by costrouc** [comment]
Completely agree that some routes e.g. this one should have more filters. I do think that filtering will be tricky since there are no standards or requirements on how build strings are named. I think that we would have to calculate dependencies
