### ISSUE TITLE
Include latest gator in jupyterhub docker image for conda-store

### ISSUE THREAD

**Issue by costrouc** [Quansight/conda-store#160]
@peytondmurray would be nice to have some documentation on how I can install the latest gator conda-store bits into https://github.com/Quansight/conda-store/blob/main/conda-store/Dockerfile. So that we can demonstrate minimal usage of gator here.

**Comment by peytondmurray** [comment]
There's a quick set of commands listed here which will get you up and running: https://github.com/Quansight/gator/tree/list-installed-conda-store-packages#development

Since you'll be using conda-store and not conda, you can ignore the `First, set up your environment` section and instead make sure your conda-store server is up and running at `localhost:5000`. Then follow the section that starts with `Clone the repo, ...` and that should get you the rest of the way. Let me know if you have issues.

**Comment by costrouc** [comment]
@peytondmurray which branch should I use?
