### ISSUE TITLE
Add documentation to get PR ready for merge

### ISSUE THREAD

**Issue by peytondmurray** [Quansight/conda-store#174]
As we get closer to merging https://github.com/mamba-org/gator/pull/155, we need to document the entire new frontend we've written for gator to handle conda-store. I propose using docblocks as the standard; @pierrotsmnrd any input you have about whether this should be a priority would be useful.

**Comment by pierrotsmnrd** [comment]
Thanks for the idea @peytondmurray 
I see two things to document : 
- the code itself - that's why you mentionned dockblock, right ? 
- the markdown with explanations on how to use Gator with conda store. It implies explaining how to setup the conda store URL in the settings, among other things.

Do you think of anything else to document ?

**Comment by pierrotsmnrd** [comment]
Following today's meeting : 
- @peytondmurray will handle the code's documentation
- I will handle the setup documentation / update the readme
