### ISSUE TITLE
Ability for exact package name match in search

### ISSUE THREAD

**Issue by costrouc** [Quansight/conda-store#263]
Right now the `search` parameter in the `/api/v1/package` and `/api/v1/build/<build-id>/packages/`. This is a fuzzy match on the package names (with plans to also be searching the description as well).

The goal is to add a (`name`? not sure what sounds best) query parameter to the routes. This should match exactly on the name of the package.

My guess for the easiest way to add this is to modify:
 - https://github.com/Quansight/conda-store/blob/main/conda-store-server/conda_store_server/api.py#L113
 - https://github.com/Quansight/conda-store/blob/main/conda-store-server/conda_store_server/api.py#L188

With a new input of either `name` add as an input to those functions and pass in from the api routes.

**Comment by pierrotsmnrd** [comment]
I'm rooting for a new param named `exact`, complementary to `search`.

Having `name` and `search` would lead to having two very similar features : retrieve package(s) by their name. 
I find it redundant, isn't it ? Also, if the user enters both parameters `name` and `search` : we have to pick one, make a choice. 
Have `exact` to refine the result of `search` is more straightforward. Using `exact` without `search` is easier, it would do nothing.

**Comment by costrouc** [comment]
So to me `search` currently isn't doing totally what I imagined. I ideally want full [text fuzzy match search](https://en.wikipedia.org/wiki/Full-text_search) over the text with the search parameter. And was thinking that the `name` field is for matches over the package name. You are right that right now `search` and `name` are almost the same at this moment but I hope to develop `search` further.

So right now there is a clash but in the future I don't expect there to be. Currently the `/api/v1/package` endpoint already takes a build parameter which allows you to match over the build string.

**Comment by gabalafou** [comment]
Totally see your point about a boolean flag. (That's why I offered alternatives because I didn't love it either to be honest.)

But just to be super clear about one thing. I need the `name` param to match exactly, character by character, i.e. like this in Python:

```python
pkg.name == query_params.name
```

Doesn't that mean that there can be only one result? Or I guess what you're saying is that the package description (or other metadata for that package) could change from version to version? And all of that could be further filtered by a search param.

I.e., I might ask for `name=python` and get back three rows of data, like so:

| name | description | version |
|------|------------ |--------|
|python|programming for everybody|1|
|python|made popular by Google|2|
|python|loved by data scientists|3|

whereas if I query `name=python` and `search=data+science`, I would only get back the third row.

The reason I'm reiterating all of this is because when I read `django-%`, I was like oh no, that is exactly what I don't want right now :smile:

Thank you so much for responding and weighing in thoughtfully.
