### ISSUE TITLE
Adding pagination to conda-store api

### ISSUE THREAD

**Issue by costrouc** [Quansight/conda-store#39]

**Comment by pierrotsmnrd** [comment]
Hi @costrouc 

This issue is common to multiple features planned in the `Conda Store UI / Gator` project. I suggest we handle it early. I'll be happy to participate in the effort of solving it.

First, let's define the expected GET parameters. What do you think is the best ? Some suggestions, ideas and questions : 
- `p` and `n` for the page and number of items per page. Maybe `page` instead of `p` ?
- Should the paging start at 0 or 1 ?
- `n=25` by default
- should we allow `n=all` to return all the items - making the `p` parameter inactive ?


Also, I listed the API endpoints that need to be compatible with the pagination. Let's check them once done.

- [ ] `GET /api/v1/namespace/` :: list namespaces
- [ ] `GET /api/v1/environment/` :: list environments
- [ ] `GET /api/v1/build/` :: list builds
- [ ] `GET /api/v1/build/<build_id>/logs/`  :: get build logs
- [ ] `GET /api/v1/channel/` :: list channels
- [ ] `GET /api/v1/package/` :: list packages

**Comment by pierrotsmnrd** [comment]
Following today's meeting, here are the choices we made : 

- the API will look like : `api/v1/package/?search=matplotlib&size=25&page=2`
- First page is page=1
- Number of pages will be returned in the result
- Size limited 100

The result should contain : status, data, and page
